# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.1
      with:
        workspace: "rust-lib"
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./c-sharp/CSharpBin.sln
    - name: Build
      run: dotnet build ./c-sharp/CSharpBin.sln --no-restore 
    - name: Test
      run: dotnet test ./c-sharp/CSharpBin.sln --no-build --verbosity normal
    - name: Set Executable bit
      run: chmod +x ./c-sharp/CSharpBin/bin/Debug/net7.0/CSharpBin
    - name: Run
      run: cd ./c-sharp/CSharpBin/bin/Debug/net7.0/ && ./CSharpBin
